[phases.setup]
nixPkgs = ['...', 'php83', 'php83Extensions.mbstring', 'php83Extensions.pdo_mysql', 'apacheHttpd']

[phases.build]
cmds = [
  'composer install --no-dev --optimize-autoloader',
  'cp .env.example .env || true',
  'php artisan key:generate --force',
  'php artisan config:cache',
  'php artisan route:cache',
  'php artisan view:cache'
]

[start]
cmd = 'apache2-foreground -D FOREGROUND'
